# Generated by Django 5.0.4 on 2024-05-01 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=200)),
                ('max_number', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=None)),
                ('longitude', models.FloatField(default=None)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='game.game')),
            ],
            options={
                'db_table': 'field',
            },
        ),
    ]
