# Generated by Django 5.0.4 on 2024-05-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('repeat', models.BooleanField(default=False)),
                ('cost', models.FloatField(default=0)),
                ('max_player', models.IntegerField(default=12)),
                ('min_player', models.IntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('keyword', models.TextField(default='[]')),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
