# Generated by Django 5.0.4 on 2024-05-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=120)),
                ('password', models.TextField()),
                ('position', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('D', 'Large'), ('GK', 'Goalkeeper')], max_length=3)),
                ('games', models.ManyToManyField(related_name='players', to='game.game')),
            ],
            options={
                'db_table': 'player',
            },
        ),
    ]
